enum LatexSymbolCategory {
  algebra,
  calculus,
  linearAlgebra,
  greek,
  logicSets,
  trigHyperbolic,
  delimiters,
  physicsGeometry,
}

extension LatexSymbolCategoryExtension on LatexSymbolCategory {
  String get label {
    switch (this) {
      case LatexSymbolCategory.algebra:
        return 'Álgebra';
      case LatexSymbolCategory.calculus:
        return 'Cálculo';
      case LatexSymbolCategory.linearAlgebra:
        return 'Álgebra Linear';
      case LatexSymbolCategory.greek:
        return 'Grego';
      case LatexSymbolCategory.logicSets:
        return 'Lógica & Conjuntos';
      case LatexSymbolCategory.trigHyperbolic:
        return 'Trig & Hiperbólica';
      case LatexSymbolCategory.delimiters:
        return 'Delimitadores';
      case LatexSymbolCategory.physicsGeometry:
        return 'Física & Geometria';
    }
  }
}

class LatexSymbolItem {
  final String label;
  final String latex;
  final String template;
  final int cursorOffset;
  final bool hasSelectionPlaceholder;
  final LatexSymbolCategory category;
  final List<String> keywords;

  const LatexSymbolItem({
    required this.label,
    required this.latex,
    required this.template,
    this.cursorOffset = 0,
    this.hasSelectionPlaceholder = false,
    required this.category,
    required this.keywords,
  });
}

const List<LatexSymbolItem> kLatexCatalog = [
  // -------------------------------------------------------------
  // 1. ÁLGEBRA & POTENCIAÇÃO
  // -------------------------------------------------------------
  LatexSymbolItem(
    label: 'Fração',
    latex: r'\frac{a}{b}',
    template: r'\frac{#SEL#}{b}',
    cursorOffset: 6,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.algebra,
    keywords: ['fracao', 'frac', 'divisao', 'quociente', 'numerator', 'denominator'],
  ),
  LatexSymbolItem(
    label: 'Expoente / Potência',
    latex: r'x^{n}',
    template: r'#SEL#^{n}',
    cursorOffset: 3,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.algebra,
    keywords: ['potencia', 'expoente', 'power', 'quadrado', 'cubo', '^'],
  ),
  LatexSymbolItem(
    label: 'Subscrito / Índice',
    latex: r'x_{i}',
    template: r'#SEL#_{i}',
    cursorOffset: 3,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.algebra,
    keywords: ['subscrito', 'indice', 'index', 'sub', '_'],
  ),
  LatexSymbolItem(
    label: 'Raiz Quadrada',
    latex: r'\sqrt{x}',
    template: r'\sqrt{#SEL#}',
    cursorOffset: 6,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.algebra,
    keywords: ['raiz', 'quadrada', 'sqrt', 'radical'],
  ),
  LatexSymbolItem(
    label: 'Raiz Enésima',
    latex: r'\sqrt[n]{x}',
    template: r'\sqrt[n]{#SEL#}',
    cursorOffset: 9,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.algebra,
    keywords: ['raiz', 'enesima', 'radical', 'grau'],
  ),
  LatexSymbolItem(
    label: 'Soma / Somatório',
    latex: r'\sum_{i=1}^{n}',
    template: r'\sum_{i=1}^{n} #SEL#',
    cursorOffset: 16,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.algebra,
    keywords: ['somatorio', 'soma', 'sum', 'sigma', 'serie'],
  ),
  LatexSymbolItem(
    label: 'Produtório',
    latex: r'\prod_{i=1}^{n}',
    template: r'\prod_{i=1}^{n} #SEL#',
    cursorOffset: 17,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.algebra,
    keywords: ['produtorio', 'produto', 'multiplicacao', 'prod', 'pi maiusculo'],
  ),
  LatexSymbolItem(
    label: 'Coprodotório',
    latex: r'\coprod_{i=1}^{n}',
    template: r'\coprod_{i=1}^{n} #SEL#',
    cursorOffset: 19,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.algebra,
    keywords: ['coprodutorio', 'coprod'],
  ),
  LatexSymbolItem(
    label: 'Binômio de Newton',
    latex: r'\binom{n}{k}',
    template: r'\binom{#SEL#}{k}',
    cursorOffset: 7,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.algebra,
    keywords: ['binomio', 'combinacao', 'binom', 'escolha', 'arranjo'],
  ),
  LatexSymbolItem(
    label: 'Multiplicação (Ponto)',
    latex: r'\cdot',
    template: r' \cdot ',
    cursorOffset: 8,
    category: LatexSymbolCategory.algebra,
    keywords: ['multiplicacao', 'ponto', 'cdot', 'vezes'],
  ),
  LatexSymbolItem(
    label: 'Multiplicação (Cruz)',
    latex: r'\times',
    template: r' \times ',
    cursorOffset: 8,
    category: LatexSymbolCategory.algebra,
    keywords: ['multiplicacao', 'vezes', 'cruz', 'times', 'cross'],
  ),
  LatexSymbolItem(
    label: 'Divisão',
    latex: r'\div',
    template: r' \div ',
    cursorOffset: 6,
    category: LatexSymbolCategory.algebra,
    keywords: ['divisao', 'dividir', 'div'],
  ),
  LatexSymbolItem(
    label: 'Mais ou Menos',
    latex: r'\pm',
    template: r' \pm ',
    cursorOffset: 5,
    category: LatexSymbolCategory.algebra,
    keywords: ['mais ou menos', 'pm', 'tolerancia'],
  ),
  LatexSymbolItem(
    label: 'Menos ou Mais',
    latex: r'\mp',
    template: r' \mp ',
    cursorOffset: 5,
    category: LatexSymbolCategory.algebra,
    keywords: ['menos ou mais', 'mp'],
  ),
  LatexSymbolItem(
    label: 'Diferente de',
    latex: r'\neq',
    template: r' \neq ',
    cursorOffset: 6,
    category: LatexSymbolCategory.algebra,
    keywords: ['diferente', 'nao igual', 'neq', 'not equal'],
  ),
  LatexSymbolItem(
    label: 'Aproximadamente',
    latex: r'\approx',
    template: r' \approx ',
    cursorOffset: 9,
    category: LatexSymbolCategory.algebra,
    keywords: ['aproximadamente', 'quase igual', 'approx', 'estimativa'],
  ),
  LatexSymbolItem(
    label: 'Proporcional a',
    latex: r'\propto',
    template: r' \propto ',
    cursorOffset: 9,
    category: LatexSymbolCategory.algebra,
    keywords: ['proporcional', 'propto', 'variacao'],
  ),
  LatexSymbolItem(
    label: 'Menor ou Igual',
    latex: r'\leq',
    template: r' \leq ',
    cursorOffset: 6,
    category: LatexSymbolCategory.algebra,
    keywords: ['menor ou igual', 'leq', 'desigualdade'],
  ),
  LatexSymbolItem(
    label: 'Maior ou Igual',
    latex: r'\geq',
    template: r' \geq ',
    cursorOffset: 6,
    category: LatexSymbolCategory.algebra,
    keywords: ['maior ou igual', 'geq', 'desigualdade'],
  ),
  LatexSymbolItem(
    label: 'Muito Menor que',
    latex: r'\ll',
    template: r' \ll ',
    cursorOffset: 5,
    category: LatexSymbolCategory.algebra,
    keywords: ['muito menor', 'll', 'desprezivel'],
  ),
  LatexSymbolItem(
    label: 'Muito Maior que',
    latex: r'\gg',
    template: r' \gg ',
    cursorOffset: 5,
    category: LatexSymbolCategory.algebra,
    keywords: ['muito maior', 'gg'],
  ),

  // -------------------------------------------------------------
  // 2. CÁLCULO (LIMITES, DERIVADAS, INTEGRAIS)
  // -------------------------------------------------------------
  LatexSymbolItem(
    label: 'Limite',
    latex: r'\lim_{x \to a}',
    template: r'\lim_{x \to a} #SEL#',
    cursorOffset: 15,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.calculus,
    keywords: ['limite', 'lim', 'tendendo', 'to', 'assintota'],
  ),
  LatexSymbolItem(
    label: 'Limite no Infinito',
    latex: r'\lim_{x \to \infty}',
    template: r'\lim_{x \to \infty} #SEL#',
    cursorOffset: 20,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.calculus,
    keywords: ['limite', 'infinito', 'lim', 'infty'],
  ),
  LatexSymbolItem(
    label: 'Derivada Total (df/dx)',
    latex: r'\frac{df}{dx}',
    template: r'\frac{d#SEL#}{dx}',
    cursorOffset: 8,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.calculus,
    keywords: ['derivada', 'diferencial', 'df', 'dx', 'taxa'],
  ),
  LatexSymbolItem(
    label: 'Derivada Segunda (d²f/dx²)',
    latex: r'\frac{d^2 f}{dx^2}',
    template: r'\frac{d^2 #SEL#}{dx^2}',
    cursorOffset: 10,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.calculus,
    keywords: ['derivada segunda', 'aceleracao', 'concavidade', 'd2'],
  ),
  LatexSymbolItem(
    label: 'Derivada Parcial',
    latex: r'\frac{\partial f}{\partial x}',
    template: r'\frac{\partial #SEL#}{\partial x}',
    cursorOffset: 16,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.calculus,
    keywords: ['derivada parcial', 'partial', 'del', 'gradiente'],
  ),
  LatexSymbolItem(
    label: 'Operador Nabla / Gradiente',
    latex: r'\nabla',
    template: r'\nabla #SEL#',
    cursorOffset: 7,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.calculus,
    keywords: ['nabla', 'gradiente', 'divergente', 'rotacional', 'del'],
  ),
  LatexSymbolItem(
    label: 'Laplaciano',
    latex: r'\nabla^2',
    template: r'\nabla^2 #SEL#',
    cursorOffset: 9,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.calculus,
    keywords: ['laplaciano', 'nabla quadrado', 'difusao'],
  ),
  LatexSymbolItem(
    label: 'Integral Indefinida',
    latex: r'\int f(x)\,dx',
    template: r'\int #SEL#\,dx',
    cursorOffset: 5,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.calculus,
    keywords: ['integral', 'indefinida', 'int', 'primitiva', 'antiderivada'],
  ),
  LatexSymbolItem(
    label: 'Integral Definida',
    latex: r'\int_{a}^{b} f(x)\,dx',
    template: r'\int_{a}^{b} #SEL#\,dx',
    cursorOffset: 15,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.calculus,
    keywords: ['integral', 'definida', 'limites', 'area', 'int'],
  ),
  LatexSymbolItem(
    label: 'Integral Dupla',
    latex: r'\iint_{D} f\,dA',
    template: r'\iint_{D} #SEL#\,dA',
    cursorOffset: 12,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.calculus,
    keywords: ['integral dupla', 'iint', 'area', 'volume'],
  ),
  LatexSymbolItem(
    label: 'Integral Tripla',
    latex: r'\iiint_{V} f\,dV',
    template: r'\iiint_{V} #SEL#\,dV',
    cursorOffset: 13,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.calculus,
    keywords: ['integral tripla', 'iiint', 'volume'],
  ),
  LatexSymbolItem(
    label: 'Integral de Linha Fechada',
    latex: r'\oint_{C} \mathbf{F}\cdot d\mathbf{r}',
    template: r'\oint_{C} #SEL#',
    cursorOffset: 11,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.calculus,
    keywords: ['integral fechada', 'oint', 'circulacao', 'curva', 'cauchy'],
  ),
  LatexSymbolItem(
    label: 'Integral de Superfície Fechada',
    latex: r'\oiint_{S} \mathbf{E}\cdot d\mathbf{A}',
    template: r'\oiint_{S} #SEL#',
    cursorOffset: 12,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.calculus,
    keywords: ['integral de superficie fechada', 'fluxo', 'gauss', 'oiint'],
  ),
  LatexSymbolItem(
    label: 'Infinito',
    latex: r'\infty',
    template: r'\infty',
    cursorOffset: 6,
    category: LatexSymbolCategory.calculus,
    keywords: ['infinito', 'infty', 'infinity'],
  ),
  LatexSymbolItem(
    label: 'Espaço Matemático Fino',
    latex: r'\,',
    template: r'\,',
    cursorOffset: 2,
    category: LatexSymbolCategory.calculus,
    keywords: ['espaco', 'fino', 'dx', 'espacamento'],
  ),

  // -------------------------------------------------------------
  // 3. ÁLGEBRA LINEAR & MATRIZES
  // -------------------------------------------------------------
  LatexSymbolItem(
    label: 'Matriz 2x2 (Colchetes)',
    latex: r'\begin{bmatrix} a & b \\ c & d \end{bmatrix}',
    template: "\\begin{bmatrix}\n  #SEL# & b \\\\\n  c & d\n\\end{bmatrix}",
    cursorOffset: 25,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.linearAlgebra,
    keywords: ['matriz', 'matrix', 'bmatrix', '2x2', 'colchetes'],
  ),
  LatexSymbolItem(
    label: 'Matriz 3x3 (Colchetes)',
    latex: r'\begin{bmatrix} a & b & c \\ d & e & f \\ g & h & i \end{bmatrix}',
    template: "\\begin{bmatrix}\n  #SEL# & b & c \\\\\n  d & e & f \\\\\n  g & h & i\n\\end{bmatrix}",
    cursorOffset: 25,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.linearAlgebra,
    keywords: ['matriz', 'matrix', 'bmatrix', '3x3', 'colchetes'],
  ),
  LatexSymbolItem(
    label: 'Matriz Parênteses (pmatrix)',
    latex: r'\begin{pmatrix} a & b \\ c & d \end{pmatrix}',
    template: "\\begin{pmatrix}\n  #SEL# & b \\\\\n  c & d\n\\end{pmatrix}",
    cursorOffset: 25,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.linearAlgebra,
    keywords: ['matriz', 'pmatrix', 'parenteses', '2x2'],
  ),
  LatexSymbolItem(
    label: 'Determinante (vmatrix)',
    latex: r'\begin{vmatrix} a & b \\ c & d \end{vmatrix}',
    template: "\\begin{vmatrix}\n  #SEL# & b \\\\\n  c & d\n\\end{vmatrix}",
    cursorOffset: 25,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.linearAlgebra,
    keywords: ['determinante', 'det', 'vmatrix', 'barras'],
  ),
  LatexSymbolItem(
    label: 'Vetor Coluna',
    latex: r'\begin{pmatrix} x \\ y \\ z \end{pmatrix}',
    template: "\\begin{pmatrix}\n  #SEL# \\\\\n  y \\\\\n  z\n\\end{pmatrix}",
    cursorOffset: 23,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.linearAlgebra,
    keywords: ['vetor', 'coluna', 'vetor coluna', 'coordenadas'],
  ),
  LatexSymbolItem(
    label: 'Vetor com Seta',
    latex: r'\vec{v}',
    template: r'\vec{#SEL#}',
    cursorOffset: 5,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.linearAlgebra,
    keywords: ['vetor', 'seta', 'vec', 'vector', 'orientado'],
  ),
  LatexSymbolItem(
    label: 'Vetor Negrito (Bold)',
    latex: r'\mathbf{v}',
    template: r'\mathbf{#SEL#}',
    cursorOffset: 8,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.linearAlgebra,
    keywords: ['negrito', 'bold', 'vetor', 'matriz', 'mathbf'],
  ),
  LatexSymbolItem(
    label: 'Vetor Unitário (Chapéu/Versor)',
    latex: r'\hat{u}',
    template: r'\hat{#SEL#}',
    cursorOffset: 5,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.linearAlgebra,
    keywords: ['chapeu', 'versor', 'unitario', 'hat'],
  ),
  LatexSymbolItem(
    label: 'Norma / Magnitude',
    latex: r'\|\mathbf{v}\|',
    template: r'\|#SEL#\|',
    cursorOffset: 2,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.linearAlgebra,
    keywords: ['norma', 'modulo', 'magnitude', 'comprimento', 'norm'],
  ),
  LatexSymbolItem(
    label: 'Produto Interno / Escalar (Bra-Ket)',
    latex: r'\langle u, v \rangle',
    template: r'\langle #SEL#, v \rangle',
    cursorOffset: 8,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.linearAlgebra,
    keywords: ['produto interno', 'escalar', 'braket', 'langle', 'rangle'],
  ),
  LatexSymbolItem(
    label: 'Transposta',
    latex: r'A^{T}',
    template: r'#SEL#^{T}',
    cursorOffset: 3,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.linearAlgebra,
    keywords: ['transposta', 'transposta de matriz', 'transpose'],
  ),
  LatexSymbolItem(
    label: 'Inversa',
    latex: r'A^{-1}',
    template: r'#SEL#^{-1}',
    cursorOffset: 4,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.linearAlgebra,
    keywords: ['inversa', 'matriz inversa', 'inverse'],
  ),
  LatexSymbolItem(
    label: 'Produto Tensorial (Otimes)',
    latex: r'\otimes',
    template: r' \otimes ',
    cursorOffset: 9,
    category: LatexSymbolCategory.linearAlgebra,
    keywords: ['produto tensorial', 'otimes', 'tensor', 'kronecker'],
  ),
  LatexSymbolItem(
    label: 'Soma Direta (Oplus)',
    latex: r'\oplus',
    template: r' \oplus ',
    cursorOffset: 8,
    category: LatexSymbolCategory.linearAlgebra,
    keywords: ['soma direta', 'oplus', 'ou exclusivo', 'xor'],
  ),

  // -------------------------------------------------------------
  // 4. ALFABETO GREGO COMPLETO (MINÚSCULAS E MAIÚSCULAS)
  // -------------------------------------------------------------
  LatexSymbolItem(label: 'Alfa', latex: r'\alpha', template: r'\alpha', cursorOffset: 6, category: LatexSymbolCategory.greek, keywords: ['alfa', 'alpha', 'angulo']),
  LatexSymbolItem(label: 'Beta', latex: r'\beta', template: r'\beta', cursorOffset: 5, category: LatexSymbolCategory.greek, keywords: ['beta', 'coeficiente']),
  LatexSymbolItem(label: 'Gama', latex: r'\gamma', template: r'\gamma', cursorOffset: 6, category: LatexSymbolCategory.greek, keywords: ['gama', 'gamma', 'fator lorentz']),
  LatexSymbolItem(label: 'Gama Maiúsculo', latex: r'\Gamma', template: r'\Gamma', cursorOffset: 6, category: LatexSymbolCategory.greek, keywords: ['gamma', 'gama maiusculo', 'funcao gamma']),
  LatexSymbolItem(label: 'Delta', latex: r'\delta', template: r'\delta', cursorOffset: 6, category: LatexSymbolCategory.greek, keywords: ['delta', 'dirac', 'kronecker']),
  LatexSymbolItem(label: 'Delta Maiúsculo (Variação)', latex: r'\Delta', template: r'\Delta', cursorOffset: 6, category: LatexSymbolCategory.greek, keywords: ['delta', 'variacao', 'discriminante', 'laplace']),
  LatexSymbolItem(label: 'Épsilon', latex: r'\epsilon', template: r'\epsilon', cursorOffset: 8, category: LatexSymbolCategory.greek, keywords: ['epsilon', 'permissividade', 'erro']),
  LatexSymbolItem(label: 'Varepsilon', latex: r'\varepsilon', template: r'\varepsilon', cursorOffset: 11, category: LatexSymbolCategory.greek, keywords: ['varepsilon', 'epsilon redondo']),
  LatexSymbolItem(label: 'Zeta', latex: r'\zeta', template: r'\zeta', cursorOffset: 5, category: LatexSymbolCategory.greek, keywords: ['zeta', 'riemann', 'amortecimento']),
  LatexSymbolItem(label: 'Eta', latex: r'\eta', template: r'\eta', cursorOffset: 4, category: LatexSymbolCategory.greek, keywords: ['eta', 'rendimento', 'viscosidade']),
  LatexSymbolItem(label: 'Teta', latex: r'\theta', template: r'\theta', cursorOffset: 6, category: LatexSymbolCategory.greek, keywords: ['teta', 'theta', 'angulo']),
  LatexSymbolItem(label: 'Teta Maiúsculo', latex: r'\Theta', template: r'\Theta', cursorOffset: 6, category: LatexSymbolCategory.greek, keywords: ['theta maiusculo', 'teta']),
  LatexSymbolItem(label: 'Iota', latex: r'\iota', template: r'\iota', cursorOffset: 5, category: LatexSymbolCategory.greek, keywords: ['iota']),
  LatexSymbolItem(label: 'Capa', latex: r'\kappa', template: r'\kappa', cursorOffset: 6, category: LatexSymbolCategory.greek, keywords: ['capa', 'kappa', 'curvatura']),
  LatexSymbolItem(label: 'Lambda', latex: r'\lambda', template: r'\lambda', cursorOffset: 8, category: LatexSymbolCategory.greek, keywords: ['lambda', 'comprimento de onda', 'autovalor']),
  LatexSymbolItem(label: 'Lambda Maiúsculo', latex: r'\Lambda', template: r'\Lambda', cursorOffset: 8, category: LatexSymbolCategory.greek, keywords: ['lambda maiusculo', 'matriz autovalores']),
  LatexSymbolItem(label: 'Mu', latex: r'\mu', template: r'\mu', cursorOffset: 3, category: LatexSymbolCategory.greek, keywords: ['mu', 'media', 'micro', 'permeabilidade']),
  LatexSymbolItem(label: 'Nu', latex: r'\nu', template: r'\nu', cursorOffset: 3, category: LatexSymbolCategory.greek, keywords: ['nu', 'frequencia', 'poisson']),
  LatexSymbolItem(label: 'Xi', latex: r'\xi', template: r'\xi', cursorOffset: 3, category: LatexSymbolCategory.greek, keywords: ['xi']),
  LatexSymbolItem(label: 'Xi Maiúsculo', latex: r'\Xi', template: r'\Xi', cursorOffset: 3, category: LatexSymbolCategory.greek, keywords: ['xi maiusculo']),
  LatexSymbolItem(label: 'Pi', latex: r'\pi', template: r'\pi', cursorOffset: 3, category: LatexSymbolCategory.greek, keywords: ['pi', 'constante', '3.14']),
  LatexSymbolItem(label: 'Pi Maiúsculo', latex: r'\Pi', template: r'\Pi', cursorOffset: 3, category: LatexSymbolCategory.greek, keywords: ['pi maiusculo', 'produto']),
  LatexSymbolItem(label: 'Rô', latex: r'\rho', template: r'\rho', cursorOffset: 4, category: LatexSymbolCategory.greek, keywords: ['ro', 'rho', 'densidade', 'raio polar']),
  LatexSymbolItem(label: 'Sigma', latex: r'\sigma', template: r'\sigma', cursorOffset: 6, category: LatexSymbolCategory.greek, keywords: ['sigma', 'desvio padrao', 'tensao']),
  LatexSymbolItem(label: 'Sigma Maiúsculo', latex: r'\Sigma', template: r'\Sigma', cursorOffset: 6, category: LatexSymbolCategory.greek, keywords: ['sigma maiusculo', 'somatorio']),
  LatexSymbolItem(label: 'Tau', latex: r'\tau', template: r'\tau', cursorOffset: 4, category: LatexSymbolCategory.greek, keywords: ['tau', 'torque', 'tempo caracteristico']),
  LatexSymbolItem(label: 'Upsilon', latex: r'\upsilon', template: r'\upsilon', cursorOffset: 8, category: LatexSymbolCategory.greek, keywords: ['upsilon']),
  LatexSymbolItem(label: 'Fi', latex: r'\phi', template: r'\phi', cursorOffset: 4, category: LatexSymbolCategory.greek, keywords: ['fi', 'phi', 'angulo', 'fase']),
  LatexSymbolItem(label: 'Varphi', latex: r'\varphi', template: r'\varphi', cursorOffset: 7, category: LatexSymbolCategory.greek, keywords: ['varphi', 'fi cursivo']),
  LatexSymbolItem(label: 'Fi Maiúsculo', latex: r'\Phi', template: r'\Phi', cursorOffset: 4, category: LatexSymbolCategory.greek, keywords: ['phi maiusculo', 'fluxo magnetico']),
  LatexSymbolItem(label: 'Chi', latex: r'\chi', template: r'\chi', cursorOffset: 4, category: LatexSymbolCategory.greek, keywords: ['chi', 'qui-quadrado']),
  LatexSymbolItem(label: 'Psi', latex: r'\psi', template: r'\psi', cursorOffset: 4, category: LatexSymbolCategory.greek, keywords: ['psi', 'funcao de onda', 'mecanica quantica']),
  LatexSymbolItem(label: 'Psi Maiúsculo', latex: r'\Psi', template: r'\Psi', cursorOffset: 4, category: LatexSymbolCategory.greek, keywords: ['psi maiusculo', 'schrodinger']),
  LatexSymbolItem(label: 'Ômega', latex: r'\omega', template: r'\omega', cursorOffset: 6, category: LatexSymbolCategory.greek, keywords: ['omega', 'frequencia angular', 'resistencia']),
  LatexSymbolItem(label: 'Ômega Maiúsculo', latex: r'\Omega', template: r'\Omega', cursorOffset: 6, category: LatexSymbolCategory.greek, keywords: ['omega maiusculo', 'ohm', 'resistencia', 'espaco amostral']),

  // -------------------------------------------------------------
  // 5. LÓGICA, CONJUNTOS & RELAÇÕES
  // -------------------------------------------------------------
  LatexSymbolItem(
    label: 'Para Todo (Quantificador Universal)',
    latex: r'\forall',
    template: r'\forall ',
    cursorOffset: 8,
    category: LatexSymbolCategory.logicSets,
    keywords: ['para todo', 'universal', 'forall', 'qualquer que seja'],
  ),
  LatexSymbolItem(
    label: 'Existe (Quantificador Existencial)',
    latex: r'\exists',
    template: r'\exists ',
    cursorOffset: 8,
    category: LatexSymbolCategory.logicSets,
    keywords: ['existe', 'exists', 'ha um'],
  ),
  LatexSymbolItem(
    label: 'Não Existe',
    latex: r'\nexists',
    template: r'\nexists ',
    cursorOffset: 9,
    category: LatexSymbolCategory.logicSets,
    keywords: ['nao existe', 'nexists'],
  ),
  LatexSymbolItem(
    label: 'Pertence a',
    latex: r'\in',
    template: r' \in ',
    cursorOffset: 5,
    category: LatexSymbolCategory.logicSets,
    keywords: ['pertence', 'in', 'esta em', 'elemento'],
  ),
  LatexSymbolItem(
    label: 'Não Pertence a',
    latex: r'\notin',
    template: r' \notin ',
    cursorOffset: 8,
    category: LatexSymbolCategory.logicSets,
    keywords: ['nao pertence', 'notin'],
  ),
  LatexSymbolItem(
    label: 'Contido em / Subconjunto',
    latex: r'\subset',
    template: r' \subset ',
    cursorOffset: 9,
    category: LatexSymbolCategory.logicSets,
    keywords: ['contido', 'subconjunto', 'subset'],
  ),
  LatexSymbolItem(
    label: 'Contido ou Igual',
    latex: r'\subseteq',
    template: r' \subseteq ',
    cursorOffset: 11,
    category: LatexSymbolCategory.logicSets,
    keywords: ['contido ou igual', 'subseteq'],
  ),
  LatexSymbolItem(
    label: 'Contém / Superconjunto',
    latex: r'\supset',
    template: r' \supset ',
    cursorOffset: 9,
    category: LatexSymbolCategory.logicSets,
    keywords: ['contem', 'superconjunto', 'supset'],
  ),
  LatexSymbolItem(
    label: 'União',
    latex: r'\cup',
    template: r' \cup ',
    cursorOffset: 6,
    category: LatexSymbolCategory.logicSets,
    keywords: ['uniao', 'cup', 'reuniao'],
  ),
  LatexSymbolItem(
    label: 'Interseção',
    latex: r'\cap',
    template: r' \cap ',
    cursorOffset: 6,
    category: LatexSymbolCategory.logicSets,
    keywords: ['intersecao', 'interseccao', 'cap'],
  ),
  LatexSymbolItem(
    label: 'Conjunto Vazio',
    latex: r'\emptyset',
    template: r'\emptyset',
    cursorOffset: 9,
    category: LatexSymbolCategory.logicSets,
    keywords: ['vazio', 'conjunto vazio', 'emptyset'],
  ),
  LatexSymbolItem(
    label: 'E Lógico (Conjunção)',
    latex: r'\land',
    template: r' \land ',
    cursorOffset: 7,
    category: LatexSymbolCategory.logicSets,
    keywords: ['e', 'e logico', 'conjuncao', 'land', 'and'],
  ),
  LatexSymbolItem(
    label: 'Ou Lógico (Disjunção)',
    latex: r'\lor',
    template: r' \lor ',
    cursorOffset: 6,
    category: LatexSymbolCategory.logicSets,
    keywords: ['ou', 'ou logico', 'disjuncao', 'lor', 'or'],
  ),
  LatexSymbolItem(
    label: 'Negação Lógica',
    latex: r'\neg',
    template: r'\neg #SEL#',
    cursorOffset: 5,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.logicSets,
    keywords: ['negacao', 'nao', 'not', 'neg'],
  ),
  LatexSymbolItem(
    label: 'Implicação (Se... então)',
    latex: r'\implies',
    template: r' \implies ',
    cursorOffset: 10,
    category: LatexSymbolCategory.logicSets,
    keywords: ['implica', 'implicacao', 'implies', 'entao', 'seta dupla'],
  ),
  LatexSymbolItem(
    label: 'Se e Somente Se (Bicondicional)',
    latex: r'\iff',
    template: r' \iff ',
    cursorOffset: 6,
    category: LatexSymbolCategory.logicSets,
    keywords: ['se e somente se', 'equivalencia', 'iff', 'bicondicional'],
  ),
  LatexSymbolItem(
    label: 'Conjunto dos Reais (R)',
    latex: r'\mathbb{R}',
    template: r'\mathbb{R}',
    cursorOffset: 10,
    category: LatexSymbolCategory.logicSets,
    keywords: ['reais', 'conjunto dos reais', 'mathbb', 'r'],
  ),
  LatexSymbolItem(
    label: 'Conjunto dos Naturais (N)',
    latex: r'\mathbb{N}',
    template: r'\mathbb{N}',
    cursorOffset: 10,
    category: LatexSymbolCategory.logicSets,
    keywords: ['naturais', 'conjunto dos naturais', 'n'],
  ),
  LatexSymbolItem(
    label: 'Conjunto dos Inteiros (Z)',
    latex: r'\mathbb{Z}',
    template: r'\mathbb{Z}',
    cursorOffset: 10,
    category: LatexSymbolCategory.logicSets,
    keywords: ['inteiros', 'conjunto dos inteiros', 'z'],
  ),
  LatexSymbolItem(
    label: 'Conjunto dos Racionais (Q)',
    latex: r'\mathbb{Q}',
    template: r'\mathbb{Q}',
    cursorOffset: 10,
    category: LatexSymbolCategory.logicSets,
    keywords: ['racionais', 'conjunto dos racionais', 'fracoes', 'q'],
  ),
  LatexSymbolItem(
    label: 'Conjunto dos Complexos (C)',
    latex: r'\mathbb{C}',
    template: r'\mathbb{C}',
    cursorOffset: 10,
    category: LatexSymbolCategory.logicSets,
    keywords: ['complexos', 'conjunto dos complexos', 'c'],
  ),

  // -------------------------------------------------------------
  // 6. TRIGONOMETRIA & FUNÇÕES HIPERBÓLICAS
  // -------------------------------------------------------------
  LatexSymbolItem(
    label: 'Seno (sin)',
    latex: r'\sin(x)',
    template: r'\sin(#SEL#)',
    cursorOffset: 5,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.trigHyperbolic,
    keywords: ['seno', 'sin', 'trigonometria'],
  ),
  LatexSymbolItem(
    label: 'Cosseno (cos)',
    latex: r'\cos(x)',
    template: r'\cos(#SEL#)',
    cursorOffset: 5,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.trigHyperbolic,
    keywords: ['cosseno', 'cos', 'trigonometria'],
  ),
  LatexSymbolItem(
    label: 'Tangente (tan)',
    latex: r'\tan(x)',
    template: r'\tan(#SEL#)',
    cursorOffset: 5,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.trigHyperbolic,
    keywords: ['tangente', 'tan', 'tg'],
  ),
  LatexSymbolItem(
    label: 'Arco Seno (arcsin)',
    latex: r'\arcsin(x)',
    template: r'\arcsin(#SEL#)',
    cursorOffset: 8,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.trigHyperbolic,
    keywords: ['arco seno', 'arcsin', 'inversa'],
  ),
  LatexSymbolItem(
    label: 'Arco Cosseno (arccos)',
    latex: r'\arccos(x)',
    template: r'\arccos(#SEL#)',
    cursorOffset: 8,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.trigHyperbolic,
    keywords: ['arco cosseno', 'arccos'],
  ),
  LatexSymbolItem(
    label: 'Arco Tangente (arctan)',
    latex: r'\arctan(x)',
    template: r'\arctan(#SEL#)',
    cursorOffset: 8,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.trigHyperbolic,
    keywords: ['arco tangente', 'arctan', 'atan'],
  ),
  LatexSymbolItem(
    label: 'Seno Hiperbólico (sinh)',
    latex: r'\sinh(x)',
    template: r'\sinh(#SEL#)',
    cursorOffset: 6,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.trigHyperbolic,
    keywords: ['seno hiperbolico', 'sinh'],
  ),
  LatexSymbolItem(
    label: 'Cosseno Hiperbólico (cosh)',
    latex: r'\cosh(x)',
    template: r'\cosh(#SEL#)',
    cursorOffset: 6,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.trigHyperbolic,
    keywords: ['cosseno hiperbolico', 'cosh', 'catenaria'],
  ),
  LatexSymbolItem(
    label: 'Tangente Hiperbólica (tanh)',
    latex: r'\tanh(x)',
    template: r'\tanh(#SEL#)',
    cursorOffset: 6,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.trigHyperbolic,
    keywords: ['tangente hiperbolica', 'tanh'],
  ),
  LatexSymbolItem(
    label: 'Secante (sec)',
    latex: r'\sec(x)',
    template: r'\sec(#SEL#)',
    cursorOffset: 5,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.trigHyperbolic,
    keywords: ['secante', 'sec'],
  ),
  LatexSymbolItem(
    label: 'Cossecante (csc)',
    latex: r'\csc(x)',
    template: r'\csc(#SEL#)',
    cursorOffset: 5,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.trigHyperbolic,
    keywords: ['cossecante', 'csc', 'cosec'],
  ),
  LatexSymbolItem(
    label: 'Cotangente (cot)',
    latex: r'\cot(x)',
    template: r'\cot(#SEL#)',
    cursorOffset: 5,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.trigHyperbolic,
    keywords: ['cotangente', 'cot', 'ctg'],
  ),
  LatexSymbolItem(
    label: 'Logaritmo Natural (ln)',
    latex: r'\ln(x)',
    template: r'\ln(#SEL#)',
    cursorOffset: 4,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.trigHyperbolic,
    keywords: ['logaritmo natural', 'ln', 'neperiano'],
  ),
  LatexSymbolItem(
    label: 'Logaritmo Base 10 / Base b',
    latex: r'\log_{10}(x)',
    template: r'\log_{b}(#SEL#)',
    cursorOffset: 9,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.trigHyperbolic,
    keywords: ['logaritmo', 'log', 'base 10'],
  ),
  LatexSymbolItem(
    label: 'Exponencial (exp / e^x)',
    latex: r'\exp(x)',
    template: r'e^{#SEL#}',
    cursorOffset: 3,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.trigHyperbolic,
    keywords: ['exponencial', 'exp', 'euler', 'e'],
  ),

  // -------------------------------------------------------------
  // 7. DELIMITADORES & ENVELOPAMENTOS DINÂMICOS
  // -------------------------------------------------------------
  LatexSymbolItem(
    label: 'Parênteses Autoajustáveis',
    latex: r'\left( x \right)',
    template: r'\left( #SEL# \right)',
    cursorOffset: 7,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.delimiters,
    keywords: ['parenteses', 'left', 'right', 'delimitador', 'ajustavel'],
  ),
  LatexSymbolItem(
    label: 'Colchetes Autoajustáveis',
    latex: r'\left[ x \right]',
    template: r'\left[ #SEL# \right]',
    cursorOffset: 7,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.delimiters,
    keywords: ['colchetes', 'brackets', 'left', 'right'],
  ),
  LatexSymbolItem(
    label: 'Chaves Autoajustáveis',
    latex: r'\left\{ x \right\}',
    template: r'\left\{ #SEL# \right\}',
    cursorOffset: 8,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.delimiters,
    keywords: ['chaves', 'braces', 'conjunto', 'curly'],
  ),
  LatexSymbolItem(
    label: 'Valor Absoluto / Módulo',
    latex: r'\left| x \right|',
    template: r'\left| #SEL# \right|',
    cursorOffset: 7,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.delimiters,
    keywords: ['modulo', 'absoluto', 'abs', 'barras'],
  ),
  LatexSymbolItem(
    label: 'Piso / Floor',
    latex: r'\lfloor x \rfloor',
    template: r'\lfloor #SEL# \rfloor',
    cursorOffset: 8,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.delimiters,
    keywords: ['piso', 'floor', 'arredondar para baixo'],
  ),
  LatexSymbolItem(
    label: 'Teto / Ceil',
    latex: r'\lceil x \rceil',
    template: r'\lceil #SEL# \rceil',
    cursorOffset: 7,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.delimiters,
    keywords: ['teto', 'ceil', 'arredondar para cima'],
  ),
  LatexSymbolItem(
    label: 'Definição por Casos (Cases)',
    latex: r'\begin{cases} x, & x \ge 0 \\ -x, & x < 0 \end{cases}',
    template: "\\begin{cases}\n  #SEL#, & \\text{se } x \\ge 0 \\\\\n  0, & \\text{caso contrario}\n\\end{cases}",
    cursorOffset: 16,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.delimiters,
    keywords: ['casos', 'cases', 'funcao por partes', 'chaves sistema'],
  ),
  LatexSymbolItem(
    label: 'Texto em Fórmula',
    latex: r'\text{texto}',
    template: r'\text{#SEL#}',
    cursorOffset: 6,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.delimiters,
    keywords: ['texto', 'text', 'palavras', 'comentario'],
  ),

  // -------------------------------------------------------------
  // 8. FÍSICA, GEOMETRIA & NOTAÇÕES AVANÇADAS
  // -------------------------------------------------------------
  LatexSymbolItem(
    label: 'Constante de Planck Reduzida (H-bar)',
    latex: r'\hbar',
    template: r'\hbar',
    cursorOffset: 5,
    category: LatexSymbolCategory.physicsGeometry,
    keywords: ['hbar', 'planck', 'mecanica quantica', 'constante'],
  ),
  LatexSymbolItem(
    label: 'Kelvin / Grau',
    latex: r'{}^\circ',
    template: r'^\circ',
    cursorOffset: 6,
    category: LatexSymbolCategory.physicsGeometry,
    keywords: ['grau', 'celsius', 'circulo', 'angulo'],
  ),
  LatexSymbolItem(
    label: 'Angstrom',
    latex: r'\text{\AA}',
    template: r'\text{\AA}',
    cursorOffset: 10,
    category: LatexSymbolCategory.physicsGeometry,
    keywords: ['angstrom', 'comprimento', 'nanometro'],
  ),
  LatexSymbolItem(
    label: 'Perpendicular a',
    latex: r'\perp',
    template: r' \perp ',
    cursorOffset: 7,
    category: LatexSymbolCategory.physicsGeometry,
    keywords: ['perpendicular', 'ortogonal', 'perp', '90 graus'],
  ),
  LatexSymbolItem(
    label: 'Paralelo a',
    latex: r'\parallel',
    template: r' \parallel ',
    cursorOffset: 11,
    category: LatexSymbolCategory.physicsGeometry,
    keywords: ['paralelo', 'parallel'],
  ),
  LatexSymbolItem(
    label: 'Ângulo Geométrico',
    latex: r'\angle ABC',
    template: r'\angle #SEL#',
    cursorOffset: 7,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.physicsGeometry,
    keywords: ['angulo', 'angle', 'geometria'],
  ),
  LatexSymbolItem(
    label: 'Triângulo / Delta Geométrico',
    latex: r'\triangle ABC',
    template: r'\triangle #SEL#',
    cursorOffset: 11,
    hasSelectionPlaceholder: true,
    category: LatexSymbolCategory.physicsGeometry,
    keywords: ['triangulo', 'triangle', 'geometria'],
  ),
  LatexSymbolItem(
    label: 'Três Pontos Horizontais (Reticências)',
    latex: r'\dots',
    template: r'\dots',
    cursorOffset: 5,
    category: LatexSymbolCategory.physicsGeometry,
    keywords: ['reticencias', 'pontos', 'dots', 'continuacao'],
  ),
  LatexSymbolItem(
    label: 'Três Pontos Centrais',
    latex: r'\cdots',
    template: r'\cdots',
    cursorOffset: 6,
    category: LatexSymbolCategory.physicsGeometry,
    keywords: ['cdots', 'pontos no meio', 'reticencias'],
  ),
  LatexSymbolItem(
    label: 'Três Pontos Verticais',
    latex: r'\vdots',
    template: r'\vdots',
    cursorOffset: 6,
    category: LatexSymbolCategory.physicsGeometry,
    keywords: ['vdots', 'pontos verticais', 'matriz'],
  ),
  LatexSymbolItem(
    label: 'Três Pontos Diagonais',
    latex: r'\ddots',
    template: r'\ddots',
    cursorOffset: 6,
    category: LatexSymbolCategory.physicsGeometry,
    keywords: ['ddots', 'pontos diagonais', 'matriz'],
  ),
];

/// Helper function to search symbols across the catalog.
List<LatexSymbolItem> searchLatexSymbols({
  String query = '',
  LatexSymbolCategory? category,
}) {
  final cleanQuery = query.trim().toLowerCase();

  return kLatexCatalog.where((item) {
    if (category != null && item.category != category) {
      return false;
    }

    if (cleanQuery.isEmpty) {
      return true;
    }

    if (item.label.toLowerCase().contains(cleanQuery)) {
      return true;
    }

    if (item.latex.toLowerCase().contains(cleanQuery)) {
      return true;
    }

    for (final kw in item.keywords) {
      if (kw.toLowerCase().contains(cleanQuery)) {
        return true;
      }
    }

    return false;
  }).toList();
}
